-- Policy Renewal Predictor — MySQL Schema
-- Run this once to initialize the database.
-- Customer data is NOT stored here; it is read from the CSV file.

CREATE DATABASE IF NOT EXISTS policy_renewal_db;
USE policy_renewal_db;

-- Stores churn predictions generated by the ML model
CREATE TABLE IF NOT EXISTS predictions (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  customer_id   INT NOT NULL,
  churn_prob    FLOAT NOT NULL,
  churn_flag    TINYINT(1) NOT NULL,
  risk_level    ENUM('High','Medium','Low') NOT NULL,
  predicted_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_customer (customer_id)
);

-- Stores LLM-generated engagement strategies
CREATE TABLE IF NOT EXISTS strategies (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  customer_id   INT NOT NULL,
  strategy_text LONGTEXT NOT NULL,
  risk_level    ENUM('High','Medium','Low'),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_customer (customer_id)
);
